// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/search-movies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.116.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";
var search_movies_default = defineTool({
  name: "search_movies",
  title: "Search movies",
  description: "Search SyncShow's movie catalog by title. Returns matching movies with id, title, year, genre, rating, and poster.",
  inputSchema: {
    query: z.string().min(1).describe("Title or partial title to search for."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("movies").select("id,title,year,genre,imdb_rating,poster_url,description,category").ilike("title", `%${query}%`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { movies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-movie.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.116.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_movie_default = defineTool2({
  name: "get_movie",
  title: "Get movie",
  description: "Fetch full details for a single SyncShow movie by its id.",
  inputSchema: {
    id: z2.string().uuid().describe("The movie id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("movies").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { movie: data }
    };
  }
});

// src/lib/mcp/tools/list-trending.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.116.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_trending_default = defineTool3({
  name: "list_trending_movies",
  title: "List trending movies",
  description: "List the top-rated / featured movies from SyncShow, ordered by IMDb rating.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Max number of results."),
    featured_only: z3.boolean().default(false).describe("If true, only return featured movies.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, featured_only }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("movies").select("id,title,year,genre,imdb_rating,poster_url,featured").order("imdb_rating", { ascending: false, nullsFirst: false }).limit(limit);
    if (featured_only) q = q.eq("featured", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { movies: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "owkdvcyvglzhgjkuahmr";
var mcp_default = defineMcp({
  name: "syncshow-mcp",
  title: "SyncShow MCP",
  version: "0.1.0",
  instructions: "Tools for SyncShow, a streaming platform. Use `search_movies` to find movies by title, `get_movie` to fetch full details by id, and `list_trending_movies` to browse top-rated titles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_movies_default, get_movie_default, list_trending_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
